apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: Dev
  name: Dev-Full
rules:
  -apiGroups: ["*"]
   resources: ["*"]
   verbs: ["get", "watch", "list", "update", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: Full
  namespace: Dev
subjects:
- kind: Group
  name: Dev
  apiGroup: rbac.authorization.k8s.io
 roleRef:
   kind: Role
   name: Dev
   apiGroup: rbac.authorization.k8s.io
